# Generated by Django 4.2.19 on 2025-02-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('cooking_time', models.PositiveIntegerField(help_text='in minutes')),
                ('ingredients', models.TextField()),
                ('difficulty', models.CharField(max_length=12)),
            ],
        ),
    ]
