# Generated by Django 4.2.19 on 2025-02-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipes_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='description',
            field=models.TextField(default='There is no description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='preparation_method',
            field=models.TextField(default='There is no preparation method.'),
            preserve_default=False,
        ),
    ]
