# Generated by Django 4.2.19 on 2025-02-22 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipes_description_recipes_preparation_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='difficulty',
        ),
    ]
