# Generated by Django 4.2.19 on 2025-02-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipes_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Intermediate', 'Intermediate'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
    ]
