# Generated by Django 4.2.19 on 2025-03-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipes_id_alter_recipes_recipe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='recipe_id',
            new_name='id',
        ),
    ]
