# Generated by Django 4.2.19 on 2025-03-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_recipe_id_recipes_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='id',
            new_name='recipe_id',
        ),
    ]
