# Generated by Django 4.2.19 on 2025-03-04 17:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_rename_id_recipes_recipe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
